name: zero_waste_kitchen
description: A mobile app to reduce food wastage by tracking inventory and suggesting recipes.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  image_picker: ^1.1.2
  flutter_barcode_scanner: ^2.0.0
  http: ^1.3.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  firebase_core: ^2.32.0
  google_mlkit_text_recognition: 0.13.1
  google_mlkit_commons: 0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
